-- MySQL Script generated by MySQL Workbench
-- qui 03 out 2019 00:08:42 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema user_ms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `user_ms` ;

-- -----------------------------------------------------
-- Schema user_ms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user_ms` ;
USE `user_ms` ;

-- -----------------------------------------------------
-- Table `user_ms`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  --`birthDay` DATE NOT NULL,
  `phoneNumber` VARCHAR(11) NOT NULL,
  `token` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;

insert into `user` values(default, 'teste', '123', '123.456.789-10',
'teste@teste.com', 'testando', '912345678', null);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
